version: "3"
services:
  strapi:
    build: .
    image: strapi/strapi
    ports:
      - "1337:1337"
    depends_on:
      - meilisearch
    tty: true
  meilisearch:
    image: getmeili/meilisearch
    command: meilisearch
    volumes:
      - ../meilisearch/data.ms:/data.ms
    ports:
      - "7700:7700"
